require:
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0

Metrics/BlockLength:
  Exclude:
    - 'config/environments/*'
    - 'config/routes.rb'
    - 'db/migrate/*'
    - 'db/schema.rb'

Metrics/MethodLength:
  Exclude:
    - 'config/environments/*'
    - 'db/schema.rb'
    - 'db/migrate/*'

Rails/BulkChangeTable:
  Enabled: false

Rails/ReversibleMigration:
  Enabled: false

Rails/SkipsModelValidations:
  Exclude:
    - 'db/migrate/*'

Style/Documentation:
  Exclude:
    - 'config/*'
    - 'db/schema.rb'
    - 'db/migrate/*'

Style/MixinUsage:
  Exclude:
    - 'bin/*'