plugins:
  - rubocop-rails
  - rubocop-minitest

require:
  - rubocop-capybara

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2

Lint/MissingSuper:
  AllowedParentClasses: ["ApplicationPresenter"]

Metrics/BlockLength:
  Exclude:
    - 'app/models/concerns/*'
    - 'config/environments/*'
    - 'config/routes.rb'
    - 'db/migrate/*'
    - 'db/schema.rb'

Metrics/MethodLength:
  CountAsOne:
    - 'array'
    - 'hash'
    - 'method_call'
  Exclude:
    - 'config/environments/*'
    - 'db/schema.rb'
    - 'db/migrate/*'

Minitest/MultipleAssertions:
  Max: 8
  Include:
    - 'test/controllers/**/*_test.rb'
    - 'test/mailers/**/*_test.rb'

Naming/AccessorMethodName:
  Exclude:
    - 'app/datatables/*'

Rails/BulkChangeTable:
  Enabled: false

Rails/ReversibleMigration:
  Enabled: false

Rails/SkipsModelValidations:
  Exclude:
    - 'db/migrate/*'

Style/Documentation:
  Exclude:
    - 'config/*'
    - 'db/schema.rb'
    - 'db/migrate/*'

Style/MixinUsage:
  Exclude:
    - 'bin/*'