version: '3.8'

services:
  app:
    build: .
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    env_file: .env
    stdin_open: true
    tty: true

volumes:
  gem_cache:
  node_modules: