version: '3.8'

services:
  app:
    build: 
      dockerfile: Dockerfile.dev
      context: .
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    env_file: .env
    stdin_open: true
    ports:
      - "3000:3000"
    tty: true

volumes:
  gem_cache:
  node_modules: