services:
  web:
    build: 
      context: .
      cache_from:
        - web:latest
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - DATABASE_HOST=db
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    volumes:
      - .:/myapp
      - gem_cache:/usr/local/bundle/gems
  db:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - DATABASE_HOST=db
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  gem_cache:
  pgdata: