version: '3.8'

services:
  web:
    build: 
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/myapp
      - gem_cache:/usr/local/bundle/gems
    env_file: .env
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DATABASE_HOST}/${POSTGRES_DB}
    stdin_open: true
    ports:
      - "3000:3000"
    tty: true
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"

volumes:
  gem_cache:
  pgdata: