services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        RUBY_VERSION: $(cat .ruby-version)
        NODE_VERSION: $(cat .node-version)
    container_name: choir-site-web
    command: foreman start -f Procfile.dev
    environment:
      - DATABASE_URL=postgresql://choir_postgres:password@postgres13:5432/
      - RAILS_ENV=development
      - SOURCE_PATH=$PWD
    networks:
      - postgres_network
    ports:
      - "3000:3000"
      - "1234:1234"
    stdin_open: true
    tty: true
    volumes:
      - .:/choir-site
      - gem_cache:/usr/local/bundle/gems

networks:
  postgres_network:
    external: true

volumes:
  gem_cache: