services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bundle exec rails server -b 0.0.0.0
    environment:
      - DATABASE_URL=postgres://choir_postgres:password@postgres13:5432
    networks:
      - postgres_network
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    volumes:
      - ../..:/myapp
      - gem_cache:/usr/local/bundle/gems

networks:
  postgres_network:
    external: true

volumes:
  gem_cache:
  pgdata:
