FROM ruby:3.0.0

RUN apt-get update -qq && apt-get install -y nodejs postgresql-client

WORKDIR /app

COPY Gemfile /app/Gemfile
COPY Gemfile.lock /app/Gemfile.lock

ENV BUNDLE_PATH /usr/local/bundle/gems

RUN bundle install --path /usr/local/bundle/gems

COPY . /app

CMD ["sh"]