services:
  web:
    build:
      context: ../..
      dockerfile: .docker/development/Dockerfile
    environment:
      - DATABASE_URL=postgres://choir_postgres:password@postgres13:5432
    networks:
      - postgres_network
    volumes:
      - ../..:/myapp
      - gem_cache:/usr/local/bundle/gems
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

networks:
  postgres_network:
    external: true

volumes:
  gem_cache:
