services:
  web:
    build:
      context: ../..   # Adjust if needed
      dockerfile: /.docker/development/Dockerfile
    depends_on:
      - db
    environment:
      - RAILS_ENV=development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - DATABASE_HOST=db
    volumes:
      - ../..:/myapp
      - gem_cache:/usr/local/bundle/gems
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  gem_cache:
  pgdata:
