default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch('DATABASE_HOST', 'postgres13') %>
  username: <%= ENV.fetch('POSTGRES_USER', 'choir_postgres') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD', 'password') %>
  port: <%= ENV.fetch("DATABASE_PORT") { 5432 } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: choirsite_dev

test:
  <<: *default
  database: choirsite_test

production:
  <<: *default
  reconnect: true
  prepared_statements: true
