name: Rails CI Pipeline

on:
  push:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres 
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: myapp_test
          DATABASE_HOST: db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Build Container
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password 
          POSTGRES_DB: myapp_test
          DATABASE_HOST: db
        run: docker build -t myapp .
      
      - name: Run Container
        run: docker run -d -p 3000:3000 --name web --link db:db myapp
            
      - name: Run Rails Minitests
        run: docker exec web bundle exec rails test