name: Rails CI Pipeline

on:
  push:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres 
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_TEST_DB: myapp_test
          DATABASE_HOST: db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t myapp .
      
      - name: Run Docker Container
        run: |
          docker run -d \
            --name myapp_container \
            -e POSTGRES_USER=postgres \
            -e POSTGRES_PASSWORD=password \
            -e POSTGRES_TEST_DB=myapp_test \
            -e DATABASE_HOST=db \
            myapp
            
      - name: Setup Database
        run: docker exec myapp_container bundle exec rails db:create db:schema:load

      - name: Run Rails Minitests
        run: docker exec myapp_container bundle exec rails test