name: Rails CI Pipeline

on:
  push:
    branches: [ master ]
    
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Docker Containers
      run: docker-compose build
    
    - name: Run Tests
      run: docker-compose run web bundle exec rails test

    - name: Cleanup
      run: docker-compose down