name: Rails CI Pipeline

on:
  push:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres 
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: myapp_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t myapp .
      
      - name: Run Docker Container
        run: |
          docker run -d \
            --name myapp_container \
            -e DATABASE_URL=postgres://postgres:password@db:5432/myapp_test \
            myapp
      
      - name: Wait for Database
        run: sleep 10 # wait for database to start

      - name: Setup Database
        run: docker exec myapp_container bundle exec rails db:create db:schema:load

      - name: Run Rails Minitests
        run: docker exec myapp_container bundle exec rails test