name: Rails CI Pipeline

on:
  push:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres 
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: myapp_test
          DATABASE_HOST: db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Build And Start Container
        run: docker-compose up -d --build
      
      - name: Setup Database
        run: docker-compose exec web bundle exec rails db:create db:schema:load
      
      - name: Run Rails Minitests
        run: docker exec web bundle exec rails test