name: Rails CI Pipeline

on:
  push:
    branches: [ master ]
    
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myapp_test

    steps:
    - uses: actions/checkout@v2

    - name: Build and Launch Docker Containers
      run: docker-compose up --build -d 
    
    - name: Run Tests
      run: docker-compose exec web bundle exec rails test